###########
# site.title, site.author.name

title:  Rezident - objasnjenje oporezivanja rada u inozemstvu od strane hrvatske Porezne uprave
description: foo
keywords: porez, tax, hrvatska, porezna, uprava, rad u inozemstvu
author:
  name: Danko Kozar


########
# more settings

collections:
  chapters:
      output: false

markdown: kramdown

kramdown:
  auto_ids: true


sass:
  sass_dir: css
  style:    expanded


exclude:
- README.md


safe: true
lsi: false
